# Generated by Django 5.1.5 on 2026-01-05 12:11

import datetime
import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюта',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Картинки',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название команды')),
                ('money_team', models.BigIntegerField(default=0, verbose_name='Деньги команды')),
                ('money_for_weak', models.FloatField(default=0, verbose_name='Недельный прирост')),
                ('boost_team', models.FloatField(default=0, verbose_name='Буст команды в процентах')),
            ],
            options={
                'verbose_name': 'Команды',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Ofice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField(default=1, verbose_name='Уровень офиса')),
                ('count_of_traders', models.IntegerField(blank=True, default=3, null=True, verbose_name='Количество трейдоров для данного уровня офиса')),
                ('comfort', models.IntegerField(verbose_name='Бонус к результату трейдеров')),
                ('safe_capacity', models.IntegerField(verbose_name='Максимум очков, которые копятся до клейма')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость уровня')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.currency', verbose_name='Тип валюты')),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офис',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('prize', models.BigIntegerField()),
                ('first_team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_season_team', to='main.team')),
                ('second_team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_season_team', to='main.team')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезон',
            },
        ),
        migrations.CreateModel(
            name='Traders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Trader')),
                ('earn_for_day', models.FloatField(verbose_name='Заработок за день')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.currency', verbose_name='Тип валюты')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.picture', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Трэйдерс',
                'verbose_name_plural': 'Трэйдерс',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='Телеграм Ид')),
                ('tg_username', models.CharField(blank=True, null=True, verbose_name='Телеграм изернейм')),
                ('tg_first_name', models.CharField(blank=True, null=True, verbose_name='Телеграм Имя')),
                ('tg_last_name', models.CharField(blank=True, null=True, verbose_name='Телеграм Фамилия')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='Фото')),
                ('first_visit', models.DateTimeField(default=main.models.get_moscow_time, verbose_name='Дата и время регистрации')),
                ('last_visit', models.DateField(default=datetime.date(2026, 1, 5), verbose_name='Дата последнего входа')),
                ('count_of_visit', models.IntegerField(default=1, verbose_name='сумма Количество заходов')),
                ('visit_without_pass', models.IntegerField(default=1, verbose_name='Количество заходов без пропусков')),
                ('is_baned', models.BooleanField(default=False)),
                ('can_take_daly_tasks', models.BooleanField(default=True, verbose_name='может выполнять дневные задания')),
                ('wallet_address', models.CharField(blank=True, null=True, verbose_name='Адрес кошелька')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='main.user', verbose_name='Кто пригласил')),
            ],
            options={
                'verbose_name': 'Юзеры',
                'verbose_name_plural': 'Юзеры',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, null=True, verbose_name='Модель')),
                ('id_product', models.IntegerField(default=0, verbose_name='id продукта')),
                ('price', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False, verbose_name='Прошли ли операция успешна')),
                ('took_regard', models.BooleanField(default=False, verbose_name='Забрал награду')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='main.user')),
            ],
            options={
                'verbose_name': 'Транзакции',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='ClaimUserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(default=main.models.get_moscow_time)),
                ('money', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_user_history', to='main.user')),
            ],
            options={
                'verbose_name': 'История Claim Users',
                'verbose_name_plural': 'История Claim Users',
            },
        ),
        migrations.CreateModel(
            name='UserOfice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userofice_ofice', to='main.ofice')),
                ('traders', models.ManyToManyField(blank=True, null=True, related_name='userofice_traders', to='main.traders', verbose_name='трейдеры')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userofice_user', to='main.user')),
            ],
            options={
                'verbose_name': 'Офисы Юзеров',
                'verbose_name_plural': 'Офисы Юзеров',
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_money', models.FloatField(default=0, verbose_name='Монета token (донат) ')),
                ('game_coin', models.BigIntegerField(default=0, verbose_name='Игровая монета')),
                ('change_team_for_pay', models.BooleanField(default=True, verbose_name='менял ли команду')),
                ('my_bank', models.IntegerField(default=0, verbose_name='Мой Банк')),
                ('earn_in_team_per_month', models.BigIntegerField(default=0, verbose_name='Всего заработано в команде')),
                ('earn_in_team_per_weak', models.IntegerField(default=0, verbose_name='Заработок за неделю')),
                ('list_of_my_traders', models.ManyToManyField(blank=True, null=True, related_name='user_traders', to='main.traders', verbose_name='Мои трейдеры')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_team', to='main.team', verbose_name='Команда')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_balance', to='main.user')),
                ('my_ofice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_team', to='main.userofice', verbose_name='Мой офис')),
            ],
            options={
                'verbose_name': 'Юзеров Баланс ',
                'verbose_name_plural': 'Юзеров Баланс ',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tg_id'], name='main_user_tg_id_10d769_idx'),
        ),
    ]
