# Generated by Django 5.1.5 on 2026-01-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='prize',
            field=models.BigIntegerField(default=10000),
        ),
    ]
