# Generated by Django 5.1.5 on 2026-01-06 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_season_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traders',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=datetime.date(2026, 1, 6), verbose_name='Дата последнего входа'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
