# Generated by Django 5.1.5 on 2026-01-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_traders_picture_team_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='money_for_day',
            field=models.FloatField(default=0, verbose_name='Дневной прирост'),
        ),
    ]
