# Generated by Django 5.1.5 on 2026-01-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_team_money_for_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='boost_team',
            field=models.FloatField(default=1, verbose_name='Буст команды в процентах'),
        ),
    ]
