# Generated by Django 5.1.5 on 2026-01-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_team_boost_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='traders',
            name='lvl',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
    ]
