# Generated by Django 5.1.5 on 2026-01-08 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_traders_lvl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='change_team_for_pay',
        ),
        migrations.AddField(
            model_name='userbalance',
            name='can_change_team_for_pay',
            field=models.BooleanField(default=True, verbose_name='может ли менять команду'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=datetime.date(2026, 1, 8), verbose_name='Дата последнего входа'),
        ),
    ]
