# Generated by Django 5.1.5 on 2026-01-08 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_userbalance_change_team_for_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='list_of_my_traders',
        ),
        migrations.RemoveField(
            model_name='userofice',
            name='traders',
        ),
        migrations.CreateModel(
            name='UserTraders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trader_user', to='main.traders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_traders', to='main.user')),
            ],
            options={
                'verbose_name': 'Трейдеры Юзеров',
                'verbose_name_plural': 'Трейдеры Юзеров',
            },
        ),
        migrations.AddField(
            model_name='userbalance',
            name='list_of_my_traders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_traders', to='main.usertraders', verbose_name='Мои трейдеры'),
        ),
        migrations.AddField(
            model_name='userofice',
            name='traders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userofice_traders', to='main.usertraders', verbose_name='трейдеры'),
        ),
    ]
