# Generated by Django 5.1.5 on 2026-01-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_userbalance_list_of_my_traders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='list_of_my_traders',
        ),
        migrations.RemoveField(
            model_name='userofice',
            name='traders',
        ),
        migrations.AddField(
            model_name='userbalance',
            name='list_of_my_traders',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_traders', to='main.usertraders', verbose_name='Мои трейдеры'),
        ),
        migrations.AddField(
            model_name='userofice',
            name='traders',
            field=models.ManyToManyField(blank=True, null=True, related_name='userofice_traders', to='main.usertraders', verbose_name='трейдеры'),
        ),
    ]
