# Generated by Django 5.1.5 on 2026-01-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_userbalance_list_of_my_traders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofice',
            name='comfort',
            field=models.FloatField(verbose_name='Бонус к результату трейдеров'),
        ),
    ]
