# Generated by Django 5.1.5 on 2026-01-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_ofice_comfort'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='losser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losser_team', to='main.team', verbose_name='Команда проигравашая сезон по очкам'),
        ),
        migrations.AddField(
            model_name='season',
            name='losser_of_weak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losser_weak_team', to='main.team', verbose_name='Команда проигравашая по очкам в прошлой неделе'),
        ),
        migrations.AddField(
            model_name='season',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_team', to='main.team', verbose_name='Команда победившая сезон по очкам'),
        ),
        migrations.AddField(
            model_name='season',
            name='winner_of_weak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_weak_team', to='main.team', verbose_name='Команда победившая по очкам в прошлой неделе'),
        ),
    ]
