# Generated by Django 5.1.5 on 2026-01-09 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_season_losser_season_losser_of_weak_season_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен ли сезон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=datetime.date(2026, 1, 9), verbose_name='Дата последнего входа'),
        ),
    ]
