# Generated by Django 5.1.5 on 2026-01-09 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_season_active_alter_user_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id_product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='model',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='took_regard',
        ),
        migrations.AlterField(
            model_name='season',
            name='first_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_season_team', to='main.team'),
        ),
        migrations.AlterField(
            model_name='season',
            name='second_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_season_team', to='main.team'),
        ),
    ]
