# Generated by Django 5.1.5 on 2026-01-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_transaction_id_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='money_for_winner',
            field=models.IntegerField(default=0, verbose_name='Деньги для выдачи по окончанию сезона'),
        ),
    ]
