# Generated by Django 5.1.5 on 2026-01-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_userbalance_money_for_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_total_profit', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='userofice',
            name='ofice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userofice_ofice', to='main.ofice'),
        ),
        migrations.AlterField(
            model_name='userofice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userofice_user', to='main.user'),
        ),
    ]
