# Generated by Django 5.1.5 on 2026-01-29 23:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_statistics_alter_userofice_ofice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=datetime.date(2026, 1, 29), verbose_name='Дата последнего входа'),
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_coins', models.IntegerField(default=0)),
                ('productivity_per_day', models.FloatField(default=0)),
                ('total_players', models.IntegerField(default=0)),
                ('total_traders', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2026, 1, 29, 20, 53, 21, 934928, tzinfo=datetime.timezone.utc))),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='main.team')),
            ],
            options={
                'verbose_name': 'Статистика Команд',
                'verbose_name_plural': 'Статистика Команд',
            },
        ),
    ]
