# Generated by Django 5.1.5 on 2026-02-01 16:29

import datetime
import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_user_last_visit_teamstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstats',
            name='season',
            field=models.ForeignKey(blank=True, default=main.models.get_default_season, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_team', to='main.season'),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 13, 29, 6, 606919, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=datetime.date(2026, 2, 1), verbose_name='Дата последнего входа'),
        ),
    ]
