# Generated by Django 5.1.5 on 2026-02-01 19:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_teamstats_season_alter_teamstats_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_coins_from_ref', models.IntegerField()),
                ('friends_are_inv', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='main.user')),
            ],
            options={
                'verbose_name': 'Статистика Юзеров',
                'verbose_name_plural': 'Статистика Юзеров',
            },
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 16, 32, 15, 524746, tzinfo=datetime.timezone.utc)),
        ),
    ]
