# Generated by Django 5.1.5 on 2026-02-01 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_userstatistics_delete_statistics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstats',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 16, 33, 56, 644557, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='friends_are_inv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='received_coins_from_ref',
            field=models.IntegerField(default=0),
        ),
    ]
