# Generated by Django 5.1.5 on 2026-02-02 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_teamstats_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='earn_in_team_per_all_time',
            field=models.BigIntegerField(default=0, verbose_name='Всего денег'),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 2, 8, 32, 25, 526717, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=datetime.date(2026, 2, 2), verbose_name='Дата последнего входа'),
        ),
    ]
