# Generated by Django 5.1.5 on 2026-02-07 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_userbalance_earn_in_team_per_all_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='price_per_change_team',
            field=models.IntegerField(default=100, verbose_name='цена на смену команды'),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 7, 11, 50, 27, 927941, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=datetime.date(2026, 2, 7), verbose_name='Дата последнего входа'),
        ),
    ]
